# In _config.yml
title: Plaststock
author: Roger Erismann, Alexis Pochelon
execute:
  execute_notebooks: False
# html:
#   extra_navbar: Built by <a href="https://hammerdirt.ch/">hammerdirt</a>
#   use_repository_button: True
# repository:
#   url: https://github.com/hammerdirt-analyst/plastock

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
 - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    html_theme_options:
      use_download_button: false
      repository_url: https://github.com/hammerdirt-analyst/plastock
      use_issues_button: true
      use_repository_button: true
      extra_navbar: Built by <a href="https://hammerdirt.ch/">hammerdirt</a>
      use_multitoc_numbering: false

      extra_footer:
        <p>
           Association pour la Sauvegarde du Léman et hammerdirt 2023
        </p>
