name: plastock_xportable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.0.3
  - matplotlib
  - scikit-learn
  - ipython
  - geopandas
  - seaborn
  - sphinx
  - jupyterlab
  - jupyter-book
  - python-slugify
  - watermark

